### ISSUE TITLE
[   INFO   ] MusicExtractorSVM: no classifier models were configured by default

### ISSUE THREAD

**Issue by pengbo-learn** [Spijkervet/CLMR#1]
what does this info mean? could I disable this info? it's quite annoying.

P.S. your code is really amazing, clean and enjoyable.

**Comment by Spijkervet** [comment]
Hi there!
I believe that's a message from the essentia package.

I think you can disable info messages with:
```
import warnings
warnings.simplefilter("ignore")
```

**Comment by pengbo-learn** [comment]
> Hi there!
> I believe that's a message from the essentia package.
> 
> I think you can disable info messages with:
> 
> ```
> import warnings
> warnings.simplefilter("ignore")
> ```

warnings.simlefilter("ignore") won't work.

However, I find the message from essentia locates in HighLowPass, which is not used in linear_evaluation.py, but is imported by default. I change the line
``` 
from torchaudio_augmentations import Compose, RandomResizedCrop
```
to 
```
from torchaudio_augmentations.compose import Compose
from torchaudio_augmentations.augmentations.random_resized_crop import RandomResizedCrop
```
then the message disappeared.

**Comment by pengbo-learn** [comment]
> Hi there!
> I believe that's a message from the essentia package.
> 
> I think you can disable info messages with:
> 
> ```
> import warnings
> warnings.simplefilter("ignore")
> ```

This won't work in linear_evaluation.py

**Comment by pengbo-learn** [comment]
> Hi there!
> I believe that's a message from the essentia package.
> 
> I think you can disable info messages with:
> 
> ```
> import warnings
> warnings.simplefilter("ignore")
> ```

Adding these lines won't work in linear_evaluation.py

However, I find the message roots in the HighLowPass in torchaudio_augmentations.__init__.py
Not a good solution but I comment the line
```
from .augmentations.high_low_pass import HighLowPass
```
since the function is not used.

Thanks a lot!

**Comment by Spijkervet** [comment]
Glad to hear you found a solution!
