### ISSUE TITLE
train by raw dataset

### ISSUE THREAD

**Issue by Breeze-Zero** [Spijkervet/CLMR#4]
Hi，I want to use this method to implement a feature of my graduation project. But how can i train a model using a raw dataset such as Universal Music? Looking forward to your reply

**Comment by Spijkervet** [comment]
Hi there!

You can follow the example in one of the unit tests of this repository:
https://github.com/Spijkervet/CLMR/blob/master/tests/test_audioset.py

You can use `from clmr.datasets import AUDIO` as a generic audio PyTorch dataloader for your music library :)
