### ISSUE TITLE
config for reproducing the provided model clmr_checkpoint_10000.pt

### ISSUE THREAD

**Issue by pengbo-learn** [Spijkervet/CLMR#5]
I trained and evaluated with the default config, which resulted in roc auc 86.3.

Then I find the config is inconsistent with the paper's golden setttings, 
```txt 
                     config.yaml        paper
batch size            48                 96
max epoches          200               1000
sample rate        16000              22050
```
I changed these params and retrained, got roc auc 87.3, a lot better. Still, it was far from the 88.5 in the paper. 

Meanwhile, finetuning linear classifier from clmr_checkpoint_10000.pt did work.

So I wonder if you could provide a config setting for reproducing the pretrained model.

**Comment by Spijkervet** [comment]
Hi there! From the looks of it, you trained at 16kHz. The paper's best results were indeed reached when training the SSL model at 22.5kHz, for 10.000 epochs. I'll update the config soon!
