### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Got 59049 and 1 in dimension 1 (The offending index is 1)

### ISSUE THREAD

**Issue by 980202006** [Spijkervet/CLMR#6]
`
aa.shape
torch.Size([1, 1])
zz.shape
torch.Size([1, 59049])
`
This is caused by RandomApply(
    p=0.6
    <torchaudio_augmentations.augmentations.pitch_shift.PitchShift object at 0x7ffaf7365350>
)

**Comment by Spijkervet** [comment]
This has been fixed in the latest commits, thanks!
