### ISSUE TITLE
the pretrained model on GTZAN

### ISSUE THREAD

**Issue by gzy-rgb** [Spijkervet/CLMR#8]
hello, I appreciate your work in music representation. But i have a question: how many epochs do you train the model for the GTZAN dataset?  Can you release the pretrained model of GTZAN?

**Comment by Spijkervet** [comment]
Hi there! In our paper, we don't pre-train on GTZAN - we only use it for linear evaluation (using a pre-trained network from either MagnaTagATune or MSD).
