### ISSUE TITLE
Import Error in colab

### ISSUE THREAD

**Issue by ghost** [Spijkervet/CLMR#9]
Hello, I'm trying to run your colab-version source code. but it seems like some ERROR here:
when I run this code:

`!git clone https://github.com/spijkervet/clmr
%cd /content/clmr
!pip install . -q`

output:

`Cloning into 'clmr'...
remote: Enumerating objects: 3460, done.
remote: Counting objects: 100% (817/817), done.
remote: Compressing objects: 100% (546/546), done.
remote: Total 3460 (delta 414), reused 579 (delta 245), pack-reused 2643
Receiving objects: 100% (3460/3460), 45.50 MiB | 29.01 MiB/s, done.
Resolving deltas: 100% (2047/2047), done.
/content/clmr
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
     |████████████████████████████████| 2.9 MB 7.9 MB/s 
     |████████████████████████████████| 1.0 MB 35.8 MB/s 
     |████████████████████████████████| 829 kB 48.7 MB/s 
     |████████████████████████████████| 596 kB 46.7 MB/s 
     |████████████████████████████████| 125 kB 46.4 MB/s 
     |████████████████████████████████| 329 kB 45.1 MB/s 
     |████████████████████████████████| 1.1 MB 40.7 MB/s 
     |████████████████████████████████| 271 kB 39.2 MB/s 
     |████████████████████████████████| 160 kB 47.2 MB/s 
     |████████████████████████████████| 192 kB 52.0 MB/s 
     |██████████████████████████████▎ | 834.1 MB 1.3 MB/s eta 0:00:38tcmalloc: large alloc 1147494400 bytes == 0x55d9faec4000 @  0x7f710baee615 0x55d9f71684cc 0x55d9f724847a 0x55d9f716b2ed 0x55d9f725ce1d 0x55d9f71dee99 0x55d9f71d99ee 0x55d9f716cbda 0x55d9f71ded00 0x55d9f71d99ee 0x55d9f716cbda 0x55d9f71db737 0x55d9f725dc66 0x55d9f71dadaf 0x55d9f725dc66 0x55d9f71dadaf 0x55d9f725dc66 0x55d9f71dadaf 0x55d9f716d039 0x55d9f71b0409 0x55d9f716bc52 0x55d9f71dec25 0x55d9f71d99ee 0x55d9f716cbda 0x55d9f71db737 0x55d9f71d99ee 0x55d9f716cbda 0x55d9f71da915 0x55d9f716cafa 0x55d9f71dac0d 0x55d9f71d99ee
     |████████████████████████████████| 881.9 MB 20 kB/s 
     |████████████████████████████████| 58 kB 5.1 MB/s 
     |████████████████████████████████| 23.3 MB 48.1 MB/s 
  Building wheel for clmr (setup.py) ... done
  Building wheel for future (setup.py) ... done
  Building wheel for julius (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.10.0 requires torch==1.9.0, but you have torch 1.10.0 which is incompatible.`

**Comment by Spijkervet** [comment]
This has been resolved as of the latest commits :) Thanks!
